version: '3'

services:
  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql
  phpmyadmin:
    build: ./phpmyadmin
    restart: always
    ports:
      - 8080:80
